export enum MutationTypes {
    SET_USER = 'SET_USER',
    UNSET_USER = 'UNSET_USER',
    SET_TOKEN = 'SET_TOKEN',
    UNSET_TOKEN = 'UNSET_TOKEN',
    ADD_TO_CART = 'ADD_TO_CART',
    UPDATE_CART = 'UPDATE_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    CLEAR_CART = 'CLEAR_CART',
}